### ISSUE TITLE
No CMakeLists.txt

### ISSUE THREAD

**Issue by colleen05** [djeada/Qt-Widgets#5]
How am I supposed to build this? There is no `CMakeLists.txt`.

**Comment by djeada** [comment]
It is a collection of independent projects. Each subfolder will have its own CMakeLists.txt.

For example [https://github.com/djeada/Qt-Widgets/blob/master/src/graphics/cpp/image_cropper](https://github.com/djeada/Qt-Widgets/blob/master/src/graphics/cpp/image_cropper)

has its CMakeLists.txt located at [https://github.com/djeada/Qt-Widgets/blob/master/src/graphics/cpp/image_cropper/CMakeLists.txt](https://github.com/djeada/Qt-Widgets/blob/master/src/graphics/cpp/image_cropper/CMakeLists.txt)

**Comment by colleen05** [comment]
Oh, duh! This is so embarrassing haha, sorry.
